In [146]:
#Importing Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [147]:
df = pd.read_csv('credit_risk_dataset.csv')

In [148]:
df.head()

person_age  person_income person_home_ownership  person_emp_length  \
0          22          59000                  RENT              123.0   
1          21           9600                   OWN                5.0   
2          25           9600              MORTGAGE                1.0   
3          23          65500                  RENT                4.0   
4          24          54400                  RENT                8.0   

  loan_intent loan_grade  loan_amnt  loan_int_rate  loan_status  \
0    PERSONAL          D      35000          16.02            1   
1   EDUCATION          B       1000          11.14            0   
2     MEDICAL          C       5500          12.87            1   
3     MEDICAL          C      35000          15.23            1   
4     MEDICAL          C      35000          14.27            1   

   loan_percent_income cb_person_default_on_file  cb_person_cred_hist_length  
0                 0.59                         Y                           3  
1                 0.10                         N                           2  
2                 0.57                         N                           3  
3                 0.53                         N                           2  
4                 0.55                         Y                           4

In [149]:
dup = df.duplicated()

In [150]:
df[dup]

person_age  person_income person_home_ownership  person_emp_length  \
15975          23          42000                  RENT                5.0   
15989          23          90000              MORTGAGE                7.0   
15995          24          48000              MORTGAGE                4.0   
16025          24          10000                  RENT                8.0   
16028          23         100000              MORTGAGE                7.0   
...           ...            ...                   ...                ...   
32010          42          39996              MORTGAGE                2.0   
32047          36         250000                  RENT                2.0   
32172          49         120000              MORTGAGE               12.0   
32259          39          40000                   OWN                4.0   
32279          43          11340                  RENT                4.0   

             loan_intent loan_grade  loan_amnt  loan_int_rate  loan_status  \
15975            VENTURE          B       6000           9.99            0   
15989          EDUCATION          B       8000          10.36            0   
15995            MEDICAL          A       4000           5.42            0   
16025           PERSONAL          A       3000           7.90            1   
16028          EDUCATION          A      15000           7.88            0   
...                  ...        ...        ...            ...          ...   
32010    HOMEIMPROVEMENT          A       2500           5.42            0   
32047  DEBTCONSOLIDATION          A      20000           7.88            0   
32172            MEDICAL          B      12000          10.99            0   
32259            VENTURE          B       1000          10.37            0   
32279          EDUCATION          C       1950            NaN            1   

       loan_percent_income cb_person_default_on_file  \
15975                 0.14                         N   
15989                 0.09                         N   
15995                 0.08                         N   
16025                 0.30                         N   
16028                 0.15                         N   
...                    ...                       ...   
32010                 0.06                         N   
32047                 0.08                         N   
32172                 0.10                         N   
32259                 0.03                         N   
32279                 0.17                         N   

       cb_person_cred_hist_length  
15975                           4  
15989                           3  
15995                           4  
16025                           3  
16028                           4  
...                           ...  
32010                          12  
32047                          17  
32172                          12  
32259                          16  
32279                          11  

[165 rows x 12 columns]

In [151]:
df.shape

(32581, 12)

In [152]:
df.drop_duplicates(inplace=True)

In [153]:
df.shape

(32416, 12)

In [154]:
from sklearn.model_selection import train_test_split, learning_curve, RandomizedSearchCV

In [155]:
X, X_test, y, y_test = train_test_split(df.drop('loan_status', axis = 1), df['loan_status'], random_state=0, test_size=0.2, stratify=df['loan_status'], shuffle=True)

In [156]:
df['loan_status'].value_counts(normalize=True)

0    0.781312
1    0.218688
Name: loan_status, dtype: float64

In [157]:
y.value_counts(normalize=True)

0    0.781313
1    0.218687
Name: loan_status, dtype: float64

In [158]:
y_test.value_counts(normalize=True)


0    0.781308
1    0.218692
Name: loan_status, dtype: float64

In [159]:
np.round(X.isna().sum()* 100 / X.shape[0], 3)

person_age                    0.000
person_income                 0.000
person_home_ownership         0.000
person_emp_length             2.800
loan_intent                   0.000
loan_grade                    0.000
loan_amnt                     0.000
loan_int_rate                 9.614
loan_percent_income           0.000
cb_person_default_on_file     0.000
cb_person_cred_hist_length    0.000
dtype: float64

In [160]:
X.shape

(25932, 11)

In [161]:
X.dropna().shape

(22763, 11)

##Data Preparation

In [162]:
df.dtypes

person_age                      int64
person_income                   int64
person_home_ownership          object
person_emp_length             float64
loan_intent                    object
loan_grade                     object
loan_amnt                       int64
loan_int_rate                 float64
loan_status                     int64
loan_percent_income           float64
cb_person_default_on_file      object
cb_person_cred_hist_length      int64
dtype: object

In [163]:
for column in df:
    if df[column].dtype == 'object':
        print(column)

person_home_ownership
loan_intent
loan_grade
cb_person_default_on_file


In [164]:
df = df.drop('person_home_ownership', axis=1)
df = df.drop('loan_intent', axis=1)
df = df.drop('loan_grade', axis=1)
df = df.drop('cb_person_default_on_file', axis=1)


In [165]:
#shows count of Rows and Column
df.shape

(32416, 8)

In [166]:
#droping loan percent income column from dataset
df = df.drop('loan_percent_income', axis=1)


In [167]:
df.shape

(32416, 7)

In [168]:
#exploring missing values
df.isna().sum()

person_age                       0
person_income                    0
person_emp_length              887
loan_amnt                        0
loan_int_rate                 3095
loan_status                      0
cb_person_cred_hist_length       0
dtype: int64

In [169]:
#filling missing values with a mean
df=df.fillna(df.mean())

In [170]:
#exploring missing values post missing value fix
df.isna().sum()

person_age                    0
person_income                 0
person_emp_length             0
loan_amnt                     0
loan_int_rate                 0
loan_status                   0
cb_person_cred_hist_length    0
dtype: int64

#Train Test Split

In [171]:
y = df.iloc[:, 0].values
X = df.iloc[:, 1:28].values

In [172]:
#Splitting the dataset into training and test (in ratio 80:20)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [173]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [176]:
#Risk Model building
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [177]:
#Model Performance
print(confusion_matrix(y_test,y_pred))


[[  0   0   2 ...   0   0   0]
 [  0   0 158 ...   0   0   0]
 [  0   0 377 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]


In [178]:
print(accuracy_score(y_test,y_pred))

0.2280999383096854


In [182]:

predictions = classifier.predict_proba(X_test)
predictions

array([[7.06004198e-05, 1.18916649e-08, 3.59389955e-08, ...,
        6.27627593e-05, 1.18241274e-05, 7.21784336e-06],
       [6.87699923e-07, 2.80567541e-02, 1.84537213e-01, ...,
        2.35199487e-12, 3.52765442e-11, 6.04795654e-12],
       [1.24588199e-07, 3.20050464e-02, 1.48743507e-01, ...,
        5.61319015e-12, 1.55547755e-11, 1.11117587e-11],
       ...,
       [3.26603914e-06, 7.16734548e-02, 2.62258012e-01, ...,
        6.89992631e-14, 3.57603772e-13, 6.05241985e-12],
       [2.07976524e-06, 4.45685612e-09, 1.45377068e-08, ...,
        8.35381912e-05, 5.89527463e-06, 1.83305706e-06],
       [2.64484020e-04, 8.43724098e-02, 1.94962149e-01, ...,
        5.15863858e-09, 3.25180778e-09, 1.43051426e-07]])